### ISSUE TITLE
Créer des personas pour le site

### ISSUE THREAD

**Issue by stephanedaviet** [code-academie/saisie-frais-kilometriques#1]
Afin de cerner les besoins des utilisateurs du logiciel, créer des personas décrivant à minima :
- le profil d'une personne saisissant ses frais,
- le profil d'une personne gérant les frais saisis.

**Comment by bdelion** [comment]
Peut-être qu'il faut aussi ajouter le personna suivant :

- le profil d'une personne administrant la solution

**Comment by stephanedaviet** [comment]
Cf. #5, #6 et #7 (et d'autres si nécessaires).
