### ISSUE TITLE
Doc & URL sur les outils utilisés

### ISSUE THREAD

**Issue by bdelion** [code-academie/saisie-frais-kilometriques#11]
Mise en place dans le Wiki de page sur les outils utilisés avec liens et descriptifs ?
Exemple : 

- https://creately.com pour Wireframes & UI Mockups

- https://fr.lipsum.com/ pour générer du contenu

Comment on structure tout ceci ?

**Comment by cdrikd** [comment]
Liens ajoutés dans le wiki
